// https://github.com/dariusk/corpora

var DATA = {
    "instruments": {
        "description": "Musical Instruments",
        "data": [
            "accordion",
            "air horn",
            "baby grand piano",
            "bagpipe",
            "banjo",
            "bass guitar",
            "bassoon",
            "bugle",
            "calliope",
            "cello",
            "clarinet",
            "clavichord",
            "concertina",
            "didgeridoo",
            "dobro",
            "dulcimer",
            "fiddle",
            "fife",
            "flugelhorn",
            "flute",
            "French horn",
            "glockenspiel",
            "grand piano",
            "guitar",
            "harmonica",
            "harp",
            "harpsichord",
            "hurdy-gurdy",
            "kazoo",
            "kick drum",
            "lute",
            "lyre",
            "mandolin",
            "marimba",
            "mellotran",
            "melodica",
            "oboe",
            "pan flute",
            "piano",
            "piccolo",
            "pipe organ",
            "saxaphone",
            "sitar",
            "sousaphone",
            "tambourine",
            "theremin",
            "trombone",
            "tuba",
            "ukulele",
            "viola",
            "violin",
            "vuvuzela",
            "washtub bass",
            "xylophone",
            "zither"
        ]
    },

    "animals": {
        "description": "Animals",
        "data":
            [
                "aardvark",
                "alligator",
                "alpaca",
                "antelope",
                "ape",
                "armadillo",
                "baboon",
                "badger",
                "bat",
                "bear",
                "beaver",
                "bison",
                "boar",
                "buffalo",
                "bull",
                "camel",
                "canary",
                "capybara",
                "cat",
                "chameleon",
                "cheetah",
                "chimpanzee",
                "chinchilla",
                "chipmunk",
                "cougar",
                "cow",
                "coyote",
                "crocodile",
                "crow",
                "deer",
                "dingo",
                "dog",
                "donkey",
                "dromedary",
                "elephant",
                "elk",
                "ewe",
                "ferret",
                "finch",
                "fish",
                "fox",
                "frog",
                "gazelle",
                "gila monster",
                "giraffe",
                "gnu",
                "goat",
                "gopher",
                "gorilla",
                "grizzly bear",
                "ground hog",
                "guinea pig",
                "hamster",
                "hedgehog",
                "hippopotamus",
                "hog",
                "horse",
                "hyena",
                "ibex",
                "iguana",
                "impala",
                "jackal",
                "jaguar",
                "kangaroo",
                "koala",
                "lamb",
                "lemur",
                "leopard",
                "lion",
                "lizard",
                "llama",
                "lynx",
                "mandrill",
                "marmoset",
                "mink",
                "mole",
                "mongoose",
                "monkey",
                "moose",
                "mountain goat",
                "mouse",
                "mule",
                "muskrat",
                "mustang",
                "mynah bird",
                "newt",
                "ocelot",
                "opossum",
                "orangutan",
                "oryx",
                "otter",
                "ox",
                "panda",
                "panther",
                "parakeet",
                "parrot",
                "pig",
                "platypus",
                "polar bear",
                "porcupine",
                "porpoise",
                "prairie dog",
                "puma",
                "rabbit",
                "raccoon",
                "ram",
                "rat",
                "reindeer",
                "reptile",
                "rhinoceros",
                "salamander",
                "seal",
                "sheep",
                "shrew",
                "silver fox",
                "skunk",
                "sloth",
                "snake",
                "squirrel",
                "tapir",
                "tiger",
                "toad",
                "turtle",
                "walrus",
                "warthog",
                "weasel",
                "whale",
                "wildcat",
                "wolf",
                "wolverine",
                "wombat",
                "woodchuck",
                "yak",
                "zebra"
            ]
    },

    "flowers": {
        "description": "Flowers",
        "data": [
            "anemone",
            "amaryllis",
            "amaranth",
            "aster",
            "azalea",
            "babys breath",
            "begonia",
            "bellflower",
            "bergamot",
            "bird of paradise",
            "bluebell",
            "bottlebrush",
            "buttercup",
            "camellias",
            "carnation",
            "chrysantemum",
            "columbine",
            "clover",
            "crocus",
            "daisy",
            "dahlia",
            "daffodil",
            "delphinium",
            "edelweiss",
            "primrose",
            "forget me not",
            "foxglove",
            "freesia",
            "gerbera daisy",
            "gladiolus",
            "hibiscus",
            "heather",
            "hyacinth",
            "holly",
            "iris",
            "jasmine",
            "ladys slipper",
            "lavender",
            "lilac",
            "lily",
            "lotus flower",
            "marigold",
            "marjoram",
            "mimosa",
            "narcissus",
            "orange blossom",
            "orchid",
            "peach blossom",
            "peony",
            "petunia",
            "rhododendron",
            "rosemary",
            "roses",
            "sage",
            "snapdragon",
            "sunflower",
            "tansy",
            "thistle",
            "thyme",
            "tulip",
            "violet",
            "water lily",
            "zinnia"
        ]
    },

    "clothes": {
        "description": "Clothing Items",
        "data": [
            "baby grow",
            "ball gown",
            "belt",
            "blazer",
            "blouse",
            "boots",
            "bow tie",
            "camisole",
            "cap",
            "cardigan",
            "cargos",
            "catsuit",
            "chemise",
            "coat",
            "corset",
            "cravat",
            "cufflinks",
            "cummerbund",
            "dinner jacket",
            "dress",
            "dressing gown",
            "dungarees",
            "fleece",
            "gloves",
            "hat",
            "hoody",
            "jacket",
            "jeans",
            "jogging suit",
            "jumper",
            "kaftan",
            "kilt",
            "knickers",
            "kurta",
            "nightgown",
            "nightwear",
            "pants",
            "pashmina",
            "polo shirt",
            "poncho",
            "pyjamas",
            "raincoat",
            "robe",
            "romper",
            "sandals",
            "sarong",
            "scarf",
            "shawl",
            "shellsuit",
            "shirt",
            "shoes",
            "shorts",
            "skirt",
            "slacks",
            "slippers",
            "socks",
            "stockings",
            "suit",
            "sunglasses",
            "sweater",
            "sweatshirt",
            "swimwear",
            "t-shirt",
            "tailcoat",
            "tie",
            "tights",
            "top",
            "tracksuit",
            "trainers",
            "trousers",
            "vest",
            "waistcoat",
            "waterproof",
            "zip"
        ]
    },

    "occupations": {
        "description": "Occupations",
        "data": [
            "accountant",
            "actor",
            "administrative assistant",
            "advertising manager",
            "aerospace engineer",
            "air traffic controller",
            "airline pilot",
            "ambulance driver",
            "anesthesiologist",
            "animator",
            "architect",
            "artist",
            "astronomer",
            "athlete",
            "author",
            "baker",
            "barber",
            "bartender",
            "biologist",
            "biomedical engineer",
            "broker",
            "builder",
            "bus driver",
            "butcher",
            "carpenter",
            "cashier",
            "chef",
            "chemist",
            "childcare worker",
            "chiropractor",
            "civil engineer",
            "cleaner",
            "coach",
            "computer programmer",
            "construction manager",
            "construction worker",
            "cook",
            "cosmetologist",
            "counselor",
            "courier",
            "customer service representative",
            "dancer",
            "data analyst",
            "database administrator",
            "dental assistant",
            "dentist",
            "dermatologist",
            "designer",
            "detective",
            "dietitian",
            "dispatcher",
            "DJ",
            "doctor",
            "driver",
            "economist",
            "editor",
            "electrician",
            "elementary school teacher",
            "engineer",
            "event planner",
            "farmer",
            "fashion designer",
            "financial advisor",
            "financial analyst",
            "firefighter",
            "fitness trainer",
            "flight attendant",
            "florist",
            "graphic designer",
            "hairdresser",
            "hairstylist",
            "high school teacher",
            "home health aide",
            "hotel manager",
            "human resources manager",
            "illustrator",
            "industrial designer",
            "interior designer",
            "interpreter",
            "investigator",
            "janitor",
            "journalist",
            "judge",
            "kindergarten teacher",
            "lawyer",
            "librarian",
            "lifeguard",
            "logistician",
            "machinist",
            "makeup artist",
            "manager",
            "marketing manager",
            "massage therapist",
            "mechanic",
            "medical assistant",
            "medical laboratory technician",
            "mental health counselor",
            "musician",
            "nurse",
            "nutritionist",
            "occupational therapist",
            "office clerk",
            "optometrist",
            "painter",
            "paramedic",
            "paralegal",
            "park ranger",
            "personal trainer",
            "pharmacist",
            "photographer",
            "physical therapist",
            "physician assistant",
            "physicist",
            "pilot",
            "plumber",
            "police officer",
            "postal worker",
            "preschool teacher",
            "producer",
            "product manager",
            "professor",
            "programmer",
            "project manager",
            "property manager",
            "psychiatrist",
            "psychologist",
            "public relations specialist",
            "radiologic technologist",
            "real estate agent",
            "receptionist",
            "registered nurse",
            "reporter",
            "research scientist",
            "retail salesperson",
            "safety inspector",
            "sales manager",
            "sales representative",
            "school counselor",
            "school principal",
            "scientist",
            "secretary",
            "security guard",
            "social worker",
            "software developer",
            "software engineer",
            "speech therapist",
            "sports coach",
            "statistician",
            "stock clerk",
            "surgeon",
            "surveyor",
            "tailor",
            "taxi driver",
            "teacher",
            "teacher assistant",
            "technical writer",
            "therapist",
            "tour guide",
            "translator",
            "travel agent",
            "truck driver",
            "tutor",
            "UX designer",
            "veterinarian",
            "veterinary assistant",
            "waiter",
            "waitress",
            "web developer",
            "welder",
            "writer",
            "zoologist"
        ]

    }



}




